layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: tobiasjohannesson
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

skills:
- name: Java
  web_url: https://docs.oracle.com/en/java/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.wmVr1W0nuF_M_OswcpjyjgHaEc%26pid%3DApi&f=1&ipt=e9d44d79c78e7aa6ba2824d539a010d8b1412785917dc173e19ba264c47edbc4&ipo=images

- name: Ruby
  web_url: https://ruby-doc.org/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.WwimAs8I3GNBN0ZiLCFxPAHaD1%26pid%3DApi&f=1&ipt=7c46bc895e32dcb5160e1a413623af1b96270a78de9262416b755577b5a6d63c&ipo=images

- name: Python
  web_url: https://docs.python.org/3/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.NpvLls8u4LJqGMhPrfbAkQHaEK%26pid%3DApi&f=1&ipt=666bb9cc456541a5e4e478b44ebfcad5bbecc85a37d54708afe6b1c07a8ad192&ipo=images

- name: C
  web_url: https://learn.microsoft.com/en-us/cpp/c-language/?view=msvc-170
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.cCoXGBgc8Lh2P2V73QBURQHaHa%26pid%3DApi&f=1&ipt=52c8da83833077110405e0f76c30fa5bbd0ee62f8393598e099e0933e91535f7&ipo=images

- name: C++
  web_url: https://learn.microsoft.com/en-us/cpp/cpp/?view=msvc-170
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.ATGcRX5jqtEN8BERDBd9CAAAAA%26pid%3DApi&f=1&ipt=5c41ea9c2d4bc96f1251d97f50158a7a212be84a57cdd664ba3c6d747069f251&ipo=images

- name: TypeScript
  web_url: https://www.typescriptlang.org/docs/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.ZK1U56Xn50U-0joKYs6bEAHaEK%26pid%3DApi&f=1&ipt=9eb722f2f3a569e7253a4eb680f8e158716cc594c90da153af5b714097751fae&ipo=images

- name: JavaScript
  web_url: https://developer.mozilla.org/en-US/docs/Web/javascript
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.e2eGZzy5DzPJaNRCwIg-7QHaDw%26pid%3DApi&f=1&ipt=d8a16a7e968c06f84f610d39c4ebeb2be12da40bf3f6a65c5bb6967eeca74706&ipo=images

- name: Amazon Web Services (AWS)
  web_url: https://aws.amazon.com/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.psHTljeUmjcPjpOqtgp0HwHaEb%26pid%3DApi&f=1&ipt=74e44eddda392954404648ae9c710351da6de979a2921e8df6f6e4f7225ecc21&ipo=images

topics:
- name: Software Development 
  web_url: https://www.ibm.com/topics/software-development
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.JUU81CE6srSqCtQfeQANmwHaEl%26pid%3DApi&f=1&ipt=2356185da7b05a17bf80841054051d5d19696391b85d9f5a8304887102f17bf2&ipo=images

- name: Technology
  web_url: https://news.mit.edu/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.P1_mVis4B0Oj8qdc1iJQSgHaEK%26pid%3DApi&f=1&ipt=66997419ff0770a7fe019c704bd501c036649c32113a99152eb3fdfd85d7075c&ipo=images

- name: Reading
  web_url: https://www.goodreads.com/
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.-GbDxd8qal1bUWwd9Th_iAHaDn%26pid%3DApi&f=1&ipt=b5b583f0556fc3886dfaf961ba6d7eb959f0adad4454b72f7099923dfa518056&ipo=images

- name: Leadership
  web_url: https://hbr.org/topic/subject/leadership
  image_url: https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.1MGbnyOi8X3C6nVPbWercAHaHW%26pid%3DApi&f=1&ipt=816f54149d51a5bd3146f1661f3311a1c1c8ed9e8e53fdc5d091e8a40665f76c&ipo=images